# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkK_oJU38K1QH73EnxFOy3Gb0nEM1-X0
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# 
# # ==========================================
# # 1) PAGE SETUP & DESCRIPTION (ข้อกำหนดข้อ 4)
# # ==========================================
# st.set_page_config(page_title="Quadratic Explorer", page_icon="📈", layout="wide")
# 
# st.title("📈 Quadratic Explorer")
# st.write("""
# **เกี่ยวกับแอปพลิเคชันนี้:** เครื่องมือสำหรับสำรวจและเรียนรู้พฤติกรรมของกราฟพาราโบลา $y = ax^2 + bx + c$
# **วิธีใช้งาน:** ใช้แถบปรับค่า (Sidebar) ด้านซ้ายมือเพื่อกำหนดค่าสัมประสิทธิ์ $a, b, c$ และปรับช่วงของแกน X ที่ต้องการรับชม
# """)
# st.markdown("---")
# 
# # ==========================================
# # 2) INPUT WIDGETS (ข้อกำหนดข้อ 1)
# # ==========================================
# with st.sidebar:
#     st.header("⚙️ กำหนดค่า Input")
# 
#     # Input 1: ค่าสัมประสิทธิ์ a, b, c
#     a = st.slider("ค่าสัมประสิทธิ์ a (ความกว้าง/ทิศทาง)", -10.0, 10.0, 1.0, 0.5)
#     b = st.slider("ค่าสัมประสิทธิ์ b", -10.0, 10.0, 0.0, 0.5)
#     c = st.slider("ค่าสัมประสิทธิ์ c (จุดตัดแกน Y)", -10.0, 10.0, 0.0, 0.5)
# 
#     st.markdown("---")
#     # Input 2: ช่วงของแกน X
#     x_min, x_max = st.slider("ช่วงของแกน X (Domain)", -50.0, 50.0, (-10.0, 10.0))
#     show_table = st.checkbox("แสดงตารางพิกัดจุด (Data Table)", value=True)
# 
# # ==========================================
# # 3) VALIDATION & CALCULATION (ข้อกำหนดข้อ 2 และ 5)
# # ==========================================
# # ตรวจสอบค่าผิดปกติ: กรณี a = 0 ไม่ใช่พาราโบลา[cite: 11, 14]
# if a == 0:
#     st.warning("⚠️ **แจ้งเตือน:** เมื่อค่า a = 0 สมการนี้จะกลายเป็นสมการเส้นตรง $y = bx + c$ ไม่ใช่กราฟพาราโบลา กรุณาปรับค่า a ให้มากกว่าหรือน้อยกว่า 0")[cite: 11, 14]
#     st.stop()  # หยุดการคำนวณส่วนที่เหลือ[cite: 11]
# 
# # คำนวณจุดยอด (Vertex)
# vertex_x = -b / (2 * a)
# vertex_y = a * (vertex_x ** 2) + (b * vertex_x) + c
# vertex_type = "จุดต่ำสุด (Minimum Point)" if a > 0 else "จุดสูงสุด (Maximum Point)"
# 
# # สร้างพิกัดแกน X และ Y ด้วย NumPy
# x_vals = np.linspace(x_min, x_max, 300)
# y_vals = a * (x_vals ** 2) + b * x_vals + c
# df = pd.DataFrame({"x": x_vals, "y": y_vals})
# 
# # ==========================================
# # 4) OUTPUT (ข้อกำหนดข้อ 3: Metric + Graph + Table)
# # ==========================================
# col1, col2 = st.columns([1, 2])
# 
# # แสดงผลส่วนที่ 1: Metric & สมการ
# with col1:
#     st.subheader("📌 สรุปข้อมูลสมการ")
# 
#     # แสดงสมการ LaTeX
#     sign_b = f"+ {b}" if b >= 0 else f"- {abs(b)}"
#     sign_c = f"+ {c}" if c >= 0 else f"- {abs(c)}"
#     st.latex(f"y = {a}x^2 {sign_b}x {sign_c}")
# 
#     # แสดง Metric สำคัญ
#     st.metric(label="ลักษณะกราฟ", value="พาราโบลาหงาย" if a > 0 else "พาราโบลาคว่ำ")
#     st.metric(label="ลักษณะจุดยอด", value=vertex_type)
#     st.metric(label="พิกัดจุดยอด (Vertex)", value=f"({vertex_x:.2f}, {vertex_y:.2f})")
# 
# # แสดงผลส่วนที่ 2: กราฟ (Graph)
# with col2:
#     st.subheader("📉 กราฟพาราโบลา")
# 
#     fig, ax = plt.subplots(figsize=(8, 5))
#     ax.plot(df["x"], df["y"], color="#1f77b4", linewidth=2.5, label=f"$y = {a}x^2 {sign_b}x {sign_c}$")
# 
#     # วาดจุดยอดและแกนสมมาตร
#     ax.scatter([vertex_x], [vertex_y], color="red", s=90, zorder=5, label=f'จุดยอด ({vertex_x:.2f}, {vertex_y:.2f})')
#     ax.axvline(x=vertex_x, color="gray", linestyle="--", alpha=0.7, label="แกนสมมาตร")
# 
#     # ตั้งค่าเส้นแกนศูนย์
#     ax.axhline(0, color="black", linewidth=0.8)
#     ax.axvline(0, color="black", linewidth=0.8)
#     ax.grid(True, linestyle=":", alpha=0.6)
#     ax.set_xlabel("x")
#     ax.set_ylabel("y")
#     ax.set_xlim(x_min, x_max)
#     ax.legend(loc="upper right")
# 
#     st.pyplot(fig)
#     plt.close(fig)
# 
# # แสดงผลส่วนที่ 3: ตารางข้อมูลและปุ่มดาวน์โหลด (Table + Download)
# if show_table:
#     st.markdown("---")
#     st.subheader("📊 ตารางแสดงตัวอย่างพิกัดจุด (Data Table)")
# 
#     sample_df = df.iloc[::20].reset_index(drop=True)
#     st.dataframe(sample_df.round(2), hide_index=True, use_container_width=True)
# 
#     csv_bytes = df.round(4).to_csv(index=False).encode("utf-8")
#     st.download_button(
#         label="📥 ดาวน์โหลดข้อมูลทั้งหมด (CSV)",
#         data=csv_bytes,
#         file_name="quadratic_data.csv",
#         mime="text/csv"
#     )

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# numpy
# pandas
# matplotlib